"""empty message

Revision ID: 8684ac27a044
Revises: 6944f1e37455
Create Date: 2020-12-03 17:55:05.079457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8684ac27a044'
down_revision = '6944f1e37455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
