"""empty message

Revision ID: ce8e6f2d80cf
Revises: 6bb02eadb091
Create Date: 2020-12-05 15:34:18.427728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8e6f2d80cf'
down_revision = '6bb02eadb091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'team_id')
    # ### end Alembic commands ###
